### ISSUE TITLE
pointer_from_objref cannot be used on immutable objects

### ISSUE THREAD

**Issue by Jovansam** [odow/PATH.jl#10] opened 2020-07-03 19:22 UTC
Not sure whether to post this on the JuliaLang discussion forum or here. But when I ran the example code you gave:

```jl
using JuMP, PATH
M = [
           0  0 -1 -1
           0  0  1 -2
           1 -1  2 -2
           1  2 -2  4
       ]
q = [2, 2, -2, -6]
model = Model(PATH.Optimizer)
set_optimizer_attribute(model, "output", "no")
@variable(model, x[1:4] >= 0)
@constraint(model, M * x .+ q ⟂ x)
optimize!(model)
value.(x)
```
I get the message displayed in the subject, "pointer_from_objref cannot be used on immutable objects". Not sure whether this is coming only from my side and how to resolve it.

Thanks for your response.

**Comment by odow** [comment] 2020-07-03 19:27
Can you post the output of
```Julia
julia> import Pkg

julia> Pkg.status("PATH")
    Status `/private/tmp/jump/Project.toml`
  [8d10db4a] PATH v0.1.1 #master (https://github.com/odow/PATH.jl)

julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

This works for me:
```Julia
julia> using JuMP, PATH
[ Info: Precompiling JuMP [4076af6c-e467-56ae-b986-b466b2749572]
[ Info: Precompiling PATH [8d10db4a-e520-11e9-3c98-0d412f7fe1fc]

julia> M = [
                  0  0 -1 -1
                  0  0  1 -2
                  1 -1  2 -2
                  1  2 -2  4
              ]
4×4 Array{Int64,2}:
 0   0  -1  -1
 0   0   1  -2
 1  -1   2  -2
 1   2  -2   4

julia> q = [2, 2, -2, -6]
4-element Array{Int64,1}:
  2
  2
 -2
 -6

julia> model = Model(PATH.Optimizer)
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: Path 5.0.03

julia> set_optimizer_attribute(model, "output", "no")
"no"

julia> @variable(model, x[1:4] >= 0)
4-element Array{VariableRef,1}:
 x[1]
 x[2]
 x[3]
 x[4]

julia> @constraint(model, M * x .+ q ⟂ x)
[-x[3] - x[4] + 2, x[3] - 2 x[4] + 2, x[1] - x[2] + 2 x[3] - 2 x[4] - 2, x[1] + 2 x[2] - 2 x[3] + 4 x[4] - 6, x[1], x[2], x[3], x[4]] ∈ MathOptInterface.Complements(4)

julia> optimize!(model)
Reading options file /var/folders/bg/dzq_hhvx1dxgy6gb5510pxj80000gn/T/jl_8Td0Io
Read of options file complete.

Path 5.0.03 (Fri Jun 26 09:58:07 2020)
Written by Todd Munson, Steven Dirkse, Youngdae Kim, and Michael Ferris

julia> value.(x)
4-element Array{Float64,1}:
 2.8               
 0.0               
 0.7999999999999998
 1.2               
```

**Comment by Jovansam** [comment] 2020-07-03 19:46
Hi @odow. Thanks for helping.

Here is the information you asked about:


Pkg.status("PATH")
```
Status `C:\Users\KitchenComputer\.julia\environments\v1.4\Project.toml`
  [8d10db4a] PATH v0.1.1 #master (https://github.com/odow/PATH.jl)
```

versioninfo()
```
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
```

I recopied the code you just provided (similar to the OP). Got the same thing.

**Comment by odow** [comment] 2020-07-03 20:08
Can you post the full error? 

I can't reproduce this on Mac or Linux, 1.3 or 1.4. I don't have access to a Windows machine, but [tests are passing on Appveyor](https://ci.appveyor.com/project/odow/path-jl/builds/33778249/job/mdn7o5s1tnkxuf6w).

Another weird thing is that PATH.jl doesn't use any immutable objects...

Are you sure this is coming from PATH/JuMP?

**Comment by Jovansam** [comment] 2020-07-03 20:49
I believe I found the problem.

Tried with Julia-Vscode and Atom-Juno. This time it worked.

In may daily use I work in Atom-Hydrogen. This (as with jupyter notebook which I also just tested) does not seem to work well with the PATH package. I have come across this problem with some other packages but did not immediately think it might the problem this time. 

But if you are interested. Below is the error.

Thanks for the help and sorry I did not think of trying Juno or Vscode first.

> pointer_from_objref cannot be used on immutable objects

>  Stacktrace:
>  [1] error(::String) at .\error.jl:33
>  [2] pointer_from_objref at .\pointer.jl:146 [inlined]
>  [3] OutputInterface at C:\Users\KitchenComputer\.julia\packages\PATH\pAms1\src\C_API.jl:49 [inlined]
>  [4] solve_mcp(::Function, ::Function, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}; nnz::Int64, silent::Bool, kwargs::Base.Iterators.Pairs{Symbol,String,Tuple{Symbol},NamedTuple{(:output,),Tuple{String}}}) at C:\Users\KitchenComputer\.julia\packages\PATH\pAms1\src\C_API.jl:459
>  [5] #solve_mcp#10 at C:\Users\KitchenComputer\.julia\packages\PATH\pAms1\src\C_API.jl:577 [inlined]
>  [6] optimize!(::PATH.Optimizer{Float64}) at C:\Users\KitchenComputer\.julia\packages\PATH\pAms1\src\MOI_wrapper.jl:204
>  [7] optimize!(::MathOptInterface.Bridges.LazyBridgeOptimizer{PATH.Optimizer{Float64}}) at C:\Users\KitchenComputer\.julia\packages\MathOptInterface\RmalA\src\Bridges\bridge_optimizer.jl:239
>  [8] optimize!(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}) at C:\Users\KitchenComputer\.julia\packages\MathOptInterface\RmalA\src\Utilities\cachingoptimizer.jl:189
>  [9] optimize!(::Model, ::Nothing; bridge_constraints::Bool, ignore_optimize_hook::Bool, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at C:\Users\KitchenComputer\.julia\packages\JuMP\YXK4e\src\optimizer_interface.jl:131
>  [10] optimize! at C:\Users\KitchenComputer\.julia\packages\JuMP\YXK4e\src\optimizer_interface.jl:107 [inlined] (repeats 2 times)
>  [11] path_test() at .\In[2]:18
>  [12] top-level scope at In[2]:22

**Comment by odow** [comment] 2020-07-03 21:01
So the issue must be that Atom-Hydrogen / Jupyter must redefine `stdout` to be an immutable stream. Which is weird. I've opened a potential fix #12, but you will lose output.

**Comment by odow** [comment] 2020-07-03 21:02
Can you test this example:
```Julia
using JuMP, PATH
M = [
           0  0 -1 -1
           0  0  1 -2
           1 -1  2 -2
           1  2 -2  4
       ]
q = [2, 2, -2, -6]
model = Model(PATH.Optimizer)
set_silent(model)
@variable(model, x[1:4] >= 0)
@constraint(model, M * x .+ q ⟂ x)
optimize!(model)
value.(x)
```

**Comment by Jovansam** [comment] 2020-07-03 21:22
I tried the new code in Atom-Juno and Jupyter. It worked!  Returned the correct solution:

```
4-element Array{Float64,1}:
 2.8
 0.0
 0.7999999999999998
 1.2
```

set_silent(model) makes all the difference!

**Comment by odow** [comment] 2020-07-03 22:23
Great. I've pushed a fix so that it will throw a warning but still work if you don't use `set_silent`.

**Closed as completed** 2020-07-03 22:22 UTC
